[package]
name = "opentide-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tree-sitter language bindings for OpenTide KQL and SPL"
build = "build.rs"

[dependencies]
opentide-core.workspace = true
tree-sitter.workspace = true

[build-dependencies]
cc.workspace = true

[dev-dependencies]
serde_json.workspace = true
